-- Mediterranean Relay seed
--
-- The old visual demo seed data has been intentionally removed.
-- Use the admin import workbook flow to add real catalog, inventory, listing,
-- and community showcase content.
--
-- Keeping this file non-destructive lets a fresh database start empty while
-- still documenting that seed data should come from curated imports, not the
-- first prototype's placeholder albums.
